### ISSUE TITLE
Can't do `combine_parents` with explicit join keys

### ISSUE THREAD

**Issue by Kukunin** [rom-rb/rom-repository#60]
I need to do `#combine_parents` with explicit join keys. 

I tried to replace `.combine_parents(one: addresses)` with `.combine(one: {address: [addresses, address_id: :id]})`, but it crashes.

I don't know other way to accomplish what I need to do. Thanks

```ruby
begin
  require 'bundler/inline'
rescue LoadError => e
  $stderr.puts 'Bundler version 1.10 or later is required.'
  raise e
end

gemfile(true) do
  source 'https://rubygems.org'
  gem 'rom'
  gem 'rom-sql'
  gem 'rom-repository'
  gem 'sqlite3'
  gem 'rspec'
end

require 'rspec/autorun'

describe ROM::Repository do
  let(:rom) { ROM.container(configuration) }
  let(:configuration) do
    ROM::Configuration.new(:sql, 'sqlite::memory').tap do |config|
      config.default.create_table(:users) do
        primary_key :id
        foreign_key :address_id, :addresses, null: false
      end

      config.default.create_table(:addresses) do
        primary_key :id
        column :street_name, String, null: false
        column :city, String, null: false
      end
    end
  end

  let(:repo) do
    Class.new(ROM::Repository[:users]) do
      relations :addresses
    end.new(rom)
  end

  before { create_user(street_name: 'street', city: 'city') }

  context 'with #combine_parents' do
    let(:relation) { repo.users.combine_parents(one: repo.addresses) }

    it 'works' do
      expect(relation.one.to_h).to include(
        address: hash_including(street_name: 'street', city: 'city')
      )
    end
  end

  context 'with #combine and explicit keys' do
    let(:relation) { repo.users.combine(one: {address: [repo.addresses, address_id: :id]}) }

    it 'works' do
      expect(relation.one.to_h).to include(
        address: hash_including(street_name: 'street', city: 'city')
      )
    end
  end

  def create_user(address)
    address_id = rom.relations[:addresses].insert(address)
    rom.relations[:users].insert(address_id: address_id)
  end
end

```

```
.F

Failures:

  1) ROM::Repository with #combine and explicit keys works
     Failure/Error:
       expect(relation.one.to_h).to include(
         address: hash_including(street_name: 'street', city: 'city')
       )

     ArgumentError:
       wrong number of arguments (given 1, expected 0)
     # /Users/kukunin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rom-3.0.1/lib/rom/relation.rb:125:in `call'
     # /Users/kukunin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rom-repository-1.0.1/lib/rom/repository/relation_proxy.rb:50:in `call'
     # /Users/kukunin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rom-3.0.1/lib/rom/relation/graph.rb:94:in `block in call'
     # /Users/kukunin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rom-3.0.1/lib/rom/relation/graph.rb:94:in `map'
     # /Users/kukunin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rom-3.0.1/lib/rom/relation/graph.rb:94:in `call'
     # /Users/kukunin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rom-3.0.1/lib/rom/relation/composite.rb:21:in `call'
     # /Users/kukunin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rom-repository-1.0.1/lib/rom/repository/relation_proxy.rb:50:in `call'
     # /Users/kukunin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rom-3.0.1/lib/rom/relation/materializable.rb:42:in `one'
     # rom_value_object_save.rb:58:in `block (3 levels) in <main>'
```
